apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-publicapi
  namespace: public
provisioner: microk8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentvolumeclaim-publicapi
  namespace: public

spec:
  storageClassName: storageclass-publicapi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi